name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-ivy-cache-
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - name: Test
        run: sbt clean coverage test
      - name: Slack notification
        if: always()
        # v2.0.2
        uses: rtCamp/action-slack-notify@96d5e2a64fc78a6b7ac13265f55bee296869967a
        env:
          SLACK_CHANNEL: ci_notify
          SLACK_USERNAME: CIBot
          SLACK_COLOR: danger
          SLACK_TITLE: CI Failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: create coverage report
        if: success()
        run: sbt coverageReport
      - name: Upload test coverage
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-${{ runner.os }}
          path: target/scala-2.13/scoverage-report/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: sbt scalafmtCheckAll
