name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-
      - name: Test
        run: sbt clean coverage test
      - name: create coverage report
        run: sbt coverageReport
      - name: Upload test coverage
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage-${{ runner.os }}
          path: target/scala-2.13/scoverage-report/

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: sbt scalafmtCheckAll
