name: Continuous Integration
on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: sbt test
#      - name: Upload test coverage
#        uses: actions/upload-artifact@v1.0.0
#        with:
#          name: test-coverage-${{ matrix.os }}-${{ matrix.node }}
#          path: coverage
